Repository pysal/inequality, pull requests merged in 2024-09, with the labels that each got.

#75 Schutz inequality measures
  docs/_static/references.bib
  docs/api.rst
  inequality/__init__.py
  inequality/atkinson.py
  inequality/schutz.py
  inequality/tests/test_atkinson.py
  inequality/tests/test_pengram.py
  inequality/tests/test_schutz.py
  notebooks/shutz.ipynb
Labels: enhancement

#80 add matplotlib as a requirement
  .pre-commit-config.yaml
  README.md
  ci/310-oldest.yaml
  ci/311-latest.yaml
  ci/312-dev.yaml
  ci/312-latest.yaml
  inequality/pen.py
  inequality/tests/test_pengram.py
  pyproject.toml
Labels: maint

#83 resolve all warnings from CI -- [2024-09-02]
  conftest.py
  inequality/pen.py
  inequality/tests/test_indices.py
  inequality/tests/test_schutz.py
Labels: CI/testing, rough edge

#84 remove [Nijkamp & Poot (2013)] citation
  inequality/_indices.py
Labels: docs
