Repository pysal/inequality, pull requests merged in 2024-08, with the labels that each got.

#69 deprecation of _indices
  .github/workflows/testing.yml
  inequality/_indices.py
  inequality/gini.py
Labels: deprecation

#72 Pengram
  ci/310-MIN.yaml
  ci/311.yaml
  ci/312-DEV.yaml
  ci/312.yaml
  docs/Makefile
  docs/api.rst
  docs/index.rst
  inequality/pen.py
  inequality/tests/test_pengram.py
  notebooks/pengram.ipynb
  notebooks/weighted.dbf
  notebooks/weighted.shp
  notebooks/weighted.shx
  pyproject.toml
Labels: enhancement

#77 reup lint+format - rename CI env
  .github/workflows/build_docs.yml
  .github/workflows/testing.yml
  .pre-commit-config.yaml
  ci/310-oldest.yaml
  ci/311-latest.yaml
  ci/312-dev.yaml
  ci/312-latest.yaml
  inequality/theil.py
  pyproject.toml
Labels: maint
