Repository pysal/inequality, pull requests merged in 2025-01, with the labels that each got.

#90 Theil doc
  docs/user-guide/measure/theil.ipynb
  inequality/theil.py
Labels: docs

#92 Documentation and landing page updates
  README.md
  docs/_static/images/pen.png
  docs/_static/images/theil.png
  docs/index.rst
  docs/user-guide/measure/gini.ipynb
  inequality/gini.py
  inequality/tests/test_theil.py
  inequality/theil.py
Labels: enhancement

#93 Fix inconsistency in efficient gini
  inequality/gini.py
  inequality/tests/test_theil.py
Labels: bug

#97 remove print statements
  inequality/utils.py
Labels: rough edge

#96 move conftest
  inequality/tests/conftest.py
Labels: CI/testing
